### ISSUE TITLE
Chignolin MD dataset?

### ISSUE THREAD

**Issue by wwang2** [coarse-graining/cgnet#191]
Hi Thanks for this nice work.

 I wonder if it is possible to also share the chignolin MD datasets for me to benchmark my models?

Thanks
Wujie

**Comment by nec4** [comment]
Hello Wujie! I will check with our collaborators and get back to you shortly.

**Comment by nec4** [comment]
Hello again! The dataset is public, so you can find the following here:

trajectories:
http://pub.htmd.org/chignolin_trajectories.tar.gz 

forces: 
http://pub.htmd.org/chignolin_forces_nowater.tar.gz

coordinates:
http://pub.htmd.org/chignolin_coords_nowater.tar.gz

and generators:
http://pub.htmd.org/chignolin_generators.tar.gz

Please let us know if you need anything else!

**Comment by wwang2** [comment]
great! @nec4  thanks for sharing the data. I will close this issue for now.
