### ISSUE TITLE
Chignolin MSM analysis Notebook

### ISSUE THREAD

**Issue by amrhamedp** [coarse-graining/cgnet#192]
Hello,
I would appreciate if you just share the notebook which did the MSM analysis using pyemma (Supp. data section E).
I am just interested in the code of the analysis not the trajectories themselves.

**Comment by nec4** [comment]
Hello - I can share this code. Could you email me at charron.nicholas.e ~at~ gmail ~dot~ com?

**Comment by amrhamedp** [comment]
@nec4 I send an email....Thank you very much in advance

**Comment by jasonzzj97** [comment]
@nec4 Can you also share with me a copy of the analysis code? I have sent you an email as well. Thank you so much!
